# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import object_server_pb2 as protos_dot_object__server__pb2


class ObjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ViolateObjectDetect = channel.unary_stream(
                '/ObjectService/ViolateObjectDetect',
                request_serializer=protos_dot_object__server__pb2.ObjectRequest.SerializeToString,
                response_deserializer=protos_dot_object__server__pb2.DetectObjResponse.FromString,
                )
        self.LeaveObjectDetect = channel.unary_stream(
                '/ObjectService/LeaveObjectDetect',
                request_serializer=protos_dot_object__server__pb2.ObjectRequest.SerializeToString,
                response_deserializer=protos_dot_object__server__pb2.DetectObjResponse.FromString,
                )
        self.ForgotObjectDetect = channel.unary_stream(
                '/ObjectService/ForgotObjectDetect',
                request_serializer=protos_dot_object__server__pb2.ObjectRequest.SerializeToString,
                response_deserializer=protos_dot_object__server__pb2.DetectObjResponse.FromString,
                )


class ObjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ViolateObjectDetect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveObjectDetect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgotObjectDetect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ViolateObjectDetect': grpc.unary_stream_rpc_method_handler(
                    servicer.ViolateObjectDetect,
                    request_deserializer=protos_dot_object__server__pb2.ObjectRequest.FromString,
                    response_serializer=protos_dot_object__server__pb2.DetectObjResponse.SerializeToString,
            ),
            'LeaveObjectDetect': grpc.unary_stream_rpc_method_handler(
                    servicer.LeaveObjectDetect,
                    request_deserializer=protos_dot_object__server__pb2.ObjectRequest.FromString,
                    response_serializer=protos_dot_object__server__pb2.DetectObjResponse.SerializeToString,
            ),
            'ForgotObjectDetect': grpc.unary_stream_rpc_method_handler(
                    servicer.ForgotObjectDetect,
                    request_deserializer=protos_dot_object__server__pb2.ObjectRequest.FromString,
                    response_serializer=protos_dot_object__server__pb2.DetectObjResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ViolateObjectDetect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ObjectService/ViolateObjectDetect',
            protos_dot_object__server__pb2.ObjectRequest.SerializeToString,
            protos_dot_object__server__pb2.DetectObjResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveObjectDetect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ObjectService/LeaveObjectDetect',
            protos_dot_object__server__pb2.ObjectRequest.SerializeToString,
            protos_dot_object__server__pb2.DetectObjResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ForgotObjectDetect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ObjectService/ForgotObjectDetect',
            protos_dot_object__server__pb2.ObjectRequest.SerializeToString,
            protos_dot_object__server__pb2.DetectObjResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
